Dataset:
  data_root: F:/dataset/crowAI/
  train_list: F:/dataset/crowAI/train.txt
  test_list: F:/dataset/crowAI/val.txt
  val_list: F:/dataset/crowAI/val.txt
  classes: 2
Train:
  workers: 0
  classes: 2
  gcn_num: [9,9]
  point_length: 30
  batch_size: 4
  train_h: 300
  train_w: 300
  train_gpu: 0
  base_lr: 0.0001
  boundary: True
  weight_decay: 0.0001
  epochs: 40
  power: 0.9
  start_epoch: 0
  evaluate: True
  batch_size_val: 1
  field: False
  print_freq: 5
  weights: out\normal_bd\train_epoch_40.pth
  save_freq: 1
  save_path: out
  segm: True
