Dataset:
  data_root: F:/dataset/crowAI/
  train_list: F:/dataset/crowAI/train.txt
  test_list: F:/dataset/crowAI/val.txt
  val_list: F:/dataset/crowAI/val.txt
  classes: 2
Train:
  workers: 0
  classes: 2
  gcn_num: [9,9]
  point_length: 30
  batch_size: 1
  train_h: 300
  train_w: 300
  train_gpu: 0
  base_lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  epochs: 50
  start_epoch: 0
  evaluate: True
  batch_size_val: 1
  power: 0.9
  print_freq: 10
  weights:  out\acm_gcn_iou\train_epoch_39.pth
  save_mask: True
  save_polygon: True
  save_freq: 1
  save_path: out
  save_prediction_json: True
